### ISSUE TITLE
IP detect is not working

### ISSUE THREAD

**Issue by luisdavim** [bernadinm/tf_dcos_core#5] opened 2017-08-24 10:33 UTC
The script is trying to copy a file that doesn't exist `/tmp/ip-detect` and DC/OS seems to be ignoring the `dcos_ip_detect_public_contents` variable.

```
cp: cannot stat '/tmp/ip-detect': No such file or directory
Extracting image from this script and loading into docker daemon, this step can take a few minutes
dcos-genconf.0ce03387884523f026-58fd0833ce81b6244f.tar
Loaded image: mesosphere/dcos-genconf:0ce03387884523f026-58fd0833ce81b6244f
ESC[33m====> EXECUTING CONFIGURATION GENERATIONESC[0m
Generating configuration files...
ESC[1;31mip_detect_contents: ip-detect script `genconf/ip-detect` must existESC[0m
"docker rm" requires at least 1 argument(s).
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]
```

**Comment by luisdavim** [comment] 2017-08-24 11:52
even if we create an empty `/tmp/ip-detect` file the `dcos_ip_detect_public_contents` does not populate it or the `genconf/ip-detect` file.

**Comment by bernadinm** [comment] 2017-08-28 20:50
Hi @luisdavim. It looks like you've attempted to use the `dcos_ip_detect_public_contents`. Ideally what you're looking for is the `dcos_ip_detect_contents` so you can simply pass in your address using your private script. I will be adding that for you inside tf_dcos_core.

**Comment by bernadinm** [comment] 2017-08-28 22:24
@luisdavim. I've just confirmed the new changes. Here is what it looks like below. 


```bash
module "ip-detect-contents" {
  source   = "github.com/bernadinm/tf_script_to_variable"
  input_script_path = "scripts/cloud/aws/ip-detect.aws.sh"
}
```

```bash
dcos_ip_detect_contents = "${module.ip-detect-contents.script}"
```

These changes will be added to bernadinm/terraform-dcos as well.

**Comment by bernadinm** [comment] 2017-09-12 18:56
@luisdavim just wanted to confirm with you if you were able to test if this `dcos_ip_detect_contents` variable that was added in PR #6 to address this?

**Comment by bernadinm** [comment] 2018-02-13 22:31
@luisdavim, thanks again for filing this issue. Since I have confirmed this fix is working on my end I assume we're all good to close this out. Let me know if you have any other questions and we can reopen this issue. Thanks again!

**Closed as completed by bernadinm** 2018-02-13 22:31 UTC
